
class AuthError(Exception):
    pass


class SocketError(Exception):
    pass
